### ISSUE TITLE
add template for slides

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/nottshcMethods#1]

**Comment by Lextuga007** [comment]
See repo https://github.com/CDU-data-science-team/presentation-template which contains the folder dependencies required to run a xaringan slide rmd.

**Comment by ChrisBeeley** [comment]
There's quite a lot of stuff in there. Can we put it in a folder called presentation_template to stop it cluttering up the repo @Lextuga007 ?

**Comment by milanwiedemann** [comment]
@ChrisBeeley we need to investigate how to add a xaringan template to an R package, I think this should be possible but we probably need to follow a specific way of adding the necessary files to the R package folder structure.

@Lextuga007 did you see a xaringan template in an R package anywhere else? if yes we could copy their approach?

**Comment by ChrisBeeley** [comment]
I think we're happy with this where it is now are we? Shall we close?

**Comment by Lextuga007** [comment]
I've looked into packages that have xaringan slides and it's possible to have a folder created as part of selecting the template through R Studio: https://github.com/Athanasiamo/uiothemes so I'm going to reopen this issue and add the necessary code.

**Comment by Lextuga007** [comment]
Need to develop and add in CDU specific slide template - need confirmation for using the CDU hex image.

**Comment by Lextuga007** [comment]
I've updated the presentation slides with a new city scape image so this will all need updating.
