### ISSUE TITLE
add the slice function I wrote that also works on databases

### ISSUE THREAD

**Issue by milanwiedemann** [CDU-data-science-team/nottshcMethods#24]
currently slice from dplyr isnt supported in dbplyr (I think)
I just need to figure out where this function currently is ... 🔍 🕵️ 👨‍💻

**Comment by Lextuga007** [comment]
Slice doesn't translate into SQL: `slice(), slice_head(), and slice_tail() are not supported since database tables have no intrinsic order.` but extended slice functions can be used, see https://dbplyr.tidyverse.org/reference/dbplyr-slice.html
