### ISSUE TITLE
I broke the GitHub actions

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/nottshcMethods#48]
Sorry I broke the nottshcMethods action https://github.com/CDU-data-science-team/nottshcMethods/actions/runs/1440006726

Not urgent at all but can you please take a look? Sorry!

(it's the name change of nhsrtheme, that's the basic problem I think)

**Comment by Lextuga007** [comment]
I've removed the package as it's not used. I'll check the GitHub Action now particularly as I've added NHSRdatasets.

**Comment by Lextuga007** [comment]
All works ok with the removal of the package.
