### ISSUE TITLE
Remove NHSRdatasets dependency

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/nottshcMethods#52]
Requires changing the vignette https://github.com/CDU-data-science-team/nottshcMethods/blob/main/vignettes/date_helper.Rmd to generating a table of dates but this is preferable to having a package dependency.

**Comment by Lextuga007** [comment]
Rather than remove add this as suggests usethis::use_package("NHSRdatasets", "suggest")

**Comment by ChrisBeeley** [comment]
I was just looking at this dependency and not liking it! Can we remove?

**Comment by Lextuga007** [comment]
Yes, I guess it's best to add a bit of dummy data instead as it's just an example showing the earliest and latest data functions.
